[project]
name = "shiny"
version = "0.1.0"
description = "Add a short description here"
authors = ["Patrick HÃ¼ther <huether@imb-mainz.de>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
pandas = ">=2.2.3,<3"
plotly_express = ">=0.4.1,<0.5"
py3dmol = ">=2.4.2,<3"
shinywidgets = ">=0.3.3,<0.4"
shiny = ">=1.2.1,<2"
